artifacts_root: artifacts


data_ingestion: #<---data ingestion y configuración 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Kokit0/End-to-End-MLP-with-MLFlow/raw/main/research/data.zip #<---link a mi data .zip en el repo
  local_data_file: artifacts/data_ingestion/data.zip #<---data sera guardada en este folder local con este nombre.
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv #<--- leeré la data desde esta carpeta del paso anterior
  STATUS_FILE: artifacts/data_validation/status.txt


